### ISSUE TITLE
Shaping issues in Malayalam

### ISSUE THREAD

**Issue by santhoshtr** [NDISCOVER/Arima-Font#33]
cons + virama + la shaping is wrong .  The shaping of ൻ+്+റ is also wrong. Sharing screenshots from Arima and Noto Sans Malayalam
![image](https://user-images.githubusercontent.com/161672/188449651-269c78fe-53e0-40f0-904f-ea98cfc261dc.png)
![image](https://user-images.githubusercontent.com/161672/188449677-26e82fda-8b4e-49af-b2d9-8bc425632202.png)

Since Arima font appeared in Google docs, it would be nice to fix them as soon as possible.
cc @davelab6

**Comment by NDISCOVER** [comment]
The shaping of ൻ+്+റ is now fixed. 
Regarding the small bellow base forms I decided to removed them as instructed by my Malayalam consultant. Vertical conjuncts are harder to read and are tied to the old malayalam script. The glyphs were kept in the font files, only the opentype code was removed, so they can be used if necessary.
Below the orientation of the Malayalam consultant:
_I would suggest you to remove feature blwf, i.e. opentype coding of all small below base forms such as ka-malayalam.below, ga-malayalam.below, gha-malayalam.below etc .
You may or may not want to keep those glyphs in the glyphset, your choice.
Unlike the old malayalam script, new malayalam script has limited conjuncts. Any other conjunct that is not there in the glyphset, will be displayed as a split conjunct, i.e. with halant form ◌് in between two base characters. But as Arima font has all below base forms, any conjunct can get formed with a small belowbase form positioned under the base character .
Now, this is not wrong, but reading such vertical conjuncts can be difficult for a native reader as he/she is more accustomed to read them as split horizontal conjuncts. Now, which conjuncts to include in the typeface is a little grey area due to the script reform that happened long back. So another suggestion would be to look at different Malayalam fonts, to check which conjuncts are included in them and consider adding those new conjuncts as well.
Incase the akhanda conjunct set is already decided, simply remove the blwf feature._

**Comment by santhoshtr** [comment]
> The shaping of ൻ+്+റ is now fixed. 

:+1:  

> Regarding the small bellow base forms I decided to removed them as instructed by my Malayalam consultant. 

I am not sure which issue you are talking about. Did somebody complain about them?

> Vertical conjuncts are harder to read and are tied to the old malayalam script. 

As a native Malayalam speaker and typeface designer, this seems to be a wrong reasoning based on wrong facts. Popular Malayalam typefaces uses many vertical conjuncts. The 1971 script reformation that recommended horizontal split conjuncts were cancelled by Government last year because of its failure and popularity of vertical conjucts. The 2022 script reformation recommends keeping all vertical conjuncts. [Here is the government order](https://kerala.gov.in/assets/malayalamfonts/ezhuththureethi.pdf)

**Comment by NDISCOVER** [comment]
Hi @santhoshtr my apologies. The last feedback I had on the vertical conjuncts was from January 2022 and the government reform, after about 51 years, happened right after that date. So please understand where this mistake comes from. 
With that said I will update the font to have vertical conjuncts again in the next few days.

**Comment by NDISCOVER** [comment]
The last update has the new reform approved vertical conjuncts
